# Generated by Django 5.0.1 on 2024-01-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, default='no name provided', max_length=1000, null=True),
        ),
    ]
