# Generated by Django 4.2 on 2024-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.tarmada.com%2Frestaurants&psig=AOvVaw0j4ythX4JVfQ5vgZgkFc88&ust=1705321802881000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCNjaha3x3IMDFQAAAAAdAAAAABAD', max_length=500),
        ),
    ]
