# Generated by Django 4.2 on 2024-02-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='stripe_payment_intent',
        ),
    ]
