# Generated by Django 4.2 on 2024-01-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/none/no_img.jpg', upload_to='images/'),
        ),
    ]
